### ISSUE TITLE
Add 5 `getToken*` APIs

### ISSUE THREAD

**Issue by skynetcapital** [skynetcapital/solanaj#48]
- https://docs.solana.com/developing/clients/jsonrpc-api#gettokenaccountbalance
- https://docs.solana.com/developing/clients/jsonrpc-api#gettokenaccountsbydelegate
- https://docs.solana.com/developing/clients/jsonrpc-api#gettokenaccountsbyowner
- https://docs.solana.com/developing/clients/jsonrpc-api#gettokenlargestaccounts
- https://docs.solana.com/developing/clients/jsonrpc-api#gettokensupply

**Comment by busligisti** [comment]
This issue can be closed, it was implemented through https://github.com/skynetcapital/solanaj/pull/71
