### ISSUE TITLE
Account.fromMnemonic

### ISSUE THREAD

**Issue by ruiyeclub** [skynetcapital/solanaj#76]
DeterministicKey child = deterministicHierarchy.get(HDUtils.parsePath("M/501H/0H/0/0"), true, true);

Solana wallet default is M/44H/501H/0H/0H,I try replace it.But it still not work.(The pubkey is not correct).

Look forward to your reply.

Thanks. ^ ^

**Comment by skynetcapital** [comment]
@ruiyeclub, I've added a method `Account.fromBip39Mnemonic`, which now works when importing a seed phrase generated by the Solana CLI.

**Comment by ruiyeclub** [comment]
The wallet address is still incorrect. I use trust wallet to import the same mnemonic words. The wallet address is inconsistent

**Comment by skynetcapital** [comment]
@ruiyeclub Trust wallet uses the derivation path`m/44'/501'/0'`, per this file: https://github.com/trustwallet/wallet-core/blob/master/coins.json#L1035

Want to try that?

**Comment by ajamaica** [comment]
I found a solution to this problem. https://github.com/skynetcapital/solanaj/pull/80

**Comment by ruiyeclub** [comment]
express heartfelt thanks
