### ISSUE TITLE
tokenManager.initializeAccount

### ISSUE THREAD

**Issue by ruiyeclub** [skynetcapital/solanaj#90]
Token wallet creation failed.
`Program log:
Program TokenkegQfeZyiNwAJbNbGKPFXCWuBvf9Ss623VQ5DA invoke [1]
Program log: Instruction: InitializeAccount
Program log: Error: InvalidAccountData
Program TokenkegQfeZyiNwAJbNbGKPFXCWuBvf9Ss623VQ5DA consumed 2144 of 200000 compute units
Program TokenkegQfeZyiNwAJbNbGKPFXCWuBvf9Ss623VQ5DA failed: invalid account data for instruction
`

**Comment by ruiyeclub** [comment]
Maybe there is something wrong with the parameters. I look forward to your reply.

**Comment by wdd906** [comment]
I met this too, how did you solve it ?
