### ISSUE TITLE
Project cannot be found on maven

### ISSUE THREAD

**Issue by makarid** [skynetcapital/solanaj#91]
Hello, i am putting the following dependency on my project but Intellij cannot find the maven repo in order to pull it.
<dependency>
        <groupId>org.p2p</groupId>
        <artifactId>solanaj</artifactId>
        <version>1.6-SNAPSHOT</version>
</dependency>

Any idea why? Thanks

**Comment by 1106035348** [comment]
> 您好，我将以下依赖项放在我的项目上，但 Intellij 无法找到 Maven 存储库来提取它。 org.p2p solanaj 1.6-快照
> 
> 知道为什么吗？谢谢

You need to compile it yourself

**Comment by 1106035348** [comment]
> 您好，我将以下依赖项提出我的项目上，但的IntelliJ无法找到的Maven库存储来 提取它。org.p2p solanaj 1.6- 快照
> 
> 知道为什么吗？谢谢

Run mvn clean install -DskipTests after cloning the project

**Comment by 1106035348** [comment]
> Hello, i am putting the following dependency on my project but Intellij cannot find the maven repo in order to pull it. org.p2p solanaj 1.6-SNAPSHOT
> 
> Any idea why? Thanks

Run mvn clean install -DskipTests after cloning the project

**Comment by makarid** [comment]
Thank you!
